"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {planSetup,applySetup}=require("../../src/runtime/setup");
const {selectContext}=require("../../src/runtime/context");
const {loadContext}=require("../../src/hooks/context-loader");
const {syncAfterTool}=require("../../src/hooks/index-sync");
const {guardToolUse}=require("../../src/hooks/scope-guard");
function fixture(t){const base=path.resolve(__dirname,"../.tmp");fs.mkdirSync(base,{recursive:true});const root=fs.mkdtempSync(path.join(base,"context-"));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));applySetup(planSetup({root,skipLegacy:true,contractTracking:"untracked",workspaces:[{id:"work",path:"work",purpose:"Work",rules:[{id:"md",kind:"extension",path:".",value:[".md"]}]},{id:"study",path:"study",purpose:"Study"}],documents:[{path:"docs/common.md",purpose:"Common",scope:"common"},{path:"docs/work.md",purpose:"Work rules",scope:"work"},{path:"docs/study.md",purpose:"Study rules",scope:"study"}]}),{approved:true});for(const n of ["common","work","study"])fs.writeFileSync(path.join(root,`docs/${n}.md`),`${n.toUpperCase()}_BODY_SENTINEL`);return root;}
test("selection reads common and selected bodies only, with a verifiable read list",t=>{const root=fixture(t);const r=selectContext(root,{cwd:path.join(root,"work")});assert.match(r.context,/COMMON_BODY_SENTINEL/);assert.match(r.context,/WORK_BODY_SENTINEL/);assert.doesNotMatch(r.context,/STUDY_BODY_SENTINEL/);assert.ok(r.files.includes("docs/work.md"));assert.ok(!r.files.includes("docs/study.md"));});
test("first use invites setup without writing anything",t=>{const root=fs.mkdtempSync(path.resolve("tests/.tmp/new-"));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const r=loadContext({cwd:root});assert.equal(r.loaded,true);assert.equal(r.onboarding,true);assert.deepEqual(fs.readdirSync(root),[]);});
test("successful file events update indexes and failed/read/index events do not",t=>{const root=fixture(t);const file=path.join(root,"work/note.md");const event={cwd:root,tool_name:"Write",tool_input:{file_path:file},tool_response:{success:true},session_id:"test"};fs.writeFileSync(file,"Hello");assert.equal(syncAfterTool(event).ok,true);const index=path.join(root,"work/_Index.md");assert.match(fs.readFileSync(index,"utf8"),/note\.md/);const before=fs.readFileSync(index,"utf8");assert.equal(syncAfterTool({...event,tool_response:{isError:true}}).skipped,true);assert.equal(syncAfterTool({...event,tool_name:"Read"}).skipped,true);assert.equal(syncAfterTool({...event,tool_input:{file_path:index}}).skipped,true);assert.equal(fs.readFileSync(index,"utf8"),before);});
test("ordinary structured writes enforce configured rules without a task contract",t=>{const root=fixture(t);const event={cwd:root,tool_name:"Write",tool_input:{file_path:path.join(root,"work/no.txt"),content:"No"}};assert.equal(guardToolUse(event).allowed,false);assert.equal(guardToolUse({...event,tool_input:{file_path:path.join(root,"work/yes.md"),content:"Yes"}}).allowed,true);assert.equal(guardToolUse({...event,tool_input:{file_path:path.join(root,"../escape.md")}}).allowed,false);});

test("mixed patches cannot hide a disallowed creation behind a deletion",t=>{const root=fixture(t);const command="*** Begin Patch\n*** Delete File: work/old.md\n*** Add File: work/bad.txt\n+bad\n*** End Patch";assert.equal(guardToolUse({cwd:root,tool_name:"apply_patch",tool_input:{command}}).allowed,false);});
test("a successful patch move updates source and destination folders",t=>{const root=fixture(t);fs.writeFileSync(path.join(root,"work/new.md"),"Moved");const command="*** Begin Patch\n*** Update File: work/old.md\n*** Move to: work/new.md\n@@\n-old\n+Moved\n*** End Patch";const r=syncAfterTool({cwd:root,tool_name:"apply_patch",tool_input:{command},tool_response:"Success. Updated the following files"});assert.equal(r.ok,true);assert.match(fs.readFileSync(path.join(root,"work/_Index.md"),"utf8"),/new\.md/);});

test("workspace switching replaces session selection and a size limit is explicit",t=>{const root=fixture(t);const {selectWorkspace}=require("../../src/runtime/context");selectWorkspace(root,"work","session");assert.equal(selectContext(root,{sessionId:"session"}).workspace,"work");selectWorkspace(root,"study","session");const r=selectContext(root,{sessionId:"session"});assert.doesNotMatch(r.context,/WORK_BODY_SENTINEL/);assert.match(r.context,/STUDY_BODY_SENTINEL/);const limited=selectContext(root,{workspace:"study",maxBytes:1});assert.ok(limited.missing.length>0);assert.equal(limited.files.length,0);});
