#!/usr/bin/env bash
# ============================================================================
# Hames installer — macOS / Linux (bash)
# ============================================================================
# Run once after cloning. Renders {{TOKEN}} placeholders in framework files,
# generates per-machine state, and prepares the system for first use.
# Idempotent: safe to re-run.
#
# Usage:
#   bash scripts/init.sh
#   CEO_NAME="Jane Doe" CEO_EMAIL="jane@example.com" bash scripts/init.sh
#   DRY_RUN=1 bash scripts/init.sh
# ============================================================================

set -euo pipefail

# ── Resolve Hames root (script's parent dir) ────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HAMES_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HAMES_ROOT_POSIX="$HAMES_ROOT"
HAMES_ROOT_ESCAPED="${HAMES_ROOT_POSIX//\//\\\\}"

DRY_RUN="${DRY_RUN:-0}"
NON_INTERACTIVE="${NON_INTERACTIVE:-0}"
prefix="[init]"
[ "$DRY_RUN" = "1" ] && prefix="[DRY-RUN]"

echo ""
echo "============================================================================"
echo " Hames installer (macOS / Linux)"
echo "============================================================================"
echo "$prefix Hames root: $HAMES_ROOT"
echo ""

# ── Step 1 — Identity tokens ────────────────────────────────────────────────
CEO_NAME="${CEO_NAME:-}"
CEO_EMAIL="${CEO_EMAIL:-}"

if [ -z "$CEO_NAME" ] && [ "$NON_INTERACTIVE" != "1" ]; then
    read -r -p "Your name (becomes {{CEO_NAME}} in framework files): " CEO_NAME
fi
if [ -z "$CEO_EMAIL" ] && [ "$NON_INTERACTIVE" != "1" ]; then
    read -r -p "Your email (optional, press Enter to skip): " CEO_EMAIL
fi

CEO_NAME="${CEO_NAME:-Hames Operator}"
CEO_EMAIL="${CEO_EMAIL:-operator@example.com}"

echo ""
echo "$prefix CEO_NAME:  $CEO_NAME"
echo "$prefix CEO_EMAIL: $CEO_EMAIL"
echo ""

# ── Step 2 — Token rendering ────────────────────────────────────────────────
echo "$prefix Rendering tokens..."
rendered_files=()

render_file () {
    local f="$1"
    local tmpfile
    tmpfile="$(mktemp)"
    # Use sed with a custom delimiter to handle slashes/backslashes in values.
    # Order matters: longest tokens first.
    sed \
        -e "s|{{HAMES_ROOT_POSIX}}|${HAMES_ROOT_POSIX//|/\\|}|g" \
        -e "s|{{HAMES_ROOT_ESCAPED}}|${HAMES_ROOT_ESCAPED//|/\\|}|g" \
        -e "s|{{HAMES_ROOT}}|${HAMES_ROOT//|/\\|}|g" \
        -e "s|{{CEO_EMAIL}}|${CEO_EMAIL//|/\\|}|g" \
        -e "s|{{CEO_NAME}}|${CEO_NAME//|/\\|}|g" \
        "$f" > "$tmpfile"
    if ! cmp -s "$f" "$tmpfile"; then
        if [ "$DRY_RUN" = "1" ]; then
            rm -f "$tmpfile"
        else
            mv "$tmpfile" "$f"
            rendered_files+=("${f#$HAMES_ROOT/}")
        fi
        return 0
    else
        rm -f "$tmpfile"
        return 1
    fi
}

# Walk all relevant text files and render
rendered=0
while IFS= read -r -d '' f; do
    case "$f" in
        */.git/*|*/node_modules/*|*/__pycache__/*) continue ;;
    esac
    case "$f" in
        *.md|*.json|*.toml|*.js|*.cjs|*.mjs|*.py|*.ps1|*.sh|*.txt|*.yml|*.yaml|*.template|*.cursorrules|*.gitattributes|*.gitignore)
            if render_file "$f"; then
                rendered=$((rendered + 1))
            fi
            ;;
    esac
done < <(find "$HAMES_ROOT" -type f -print0)

echo "$prefix   files rendered: $rendered"

if [ "$DRY_RUN" != "1" ] && [ "${#rendered_files[@]}" -gt 0 ] && [ -d "$HAMES_ROOT/.git" ]; then
    tracked_rendered=()
    for rel in "${rendered_files[@]}"; do
        if git -C "$HAMES_ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1; then
            tracked_rendered+=("$rel")
        fi
    done
    if [ "${#tracked_rendered[@]}" -gt 0 ]; then
        if git -C "$HAMES_ROOT" update-index --skip-worktree -- "${tracked_rendered[@]}"; then
            echo "$prefix marked rendered framework files as local-only for clean git status"
        else
            echo "$prefix could not mark rendered files local-only (non-fatal)"
        fi
    fi
fi

# ── Step 3 — Per-machine state files ────────────────────────────────────────
LOCK_FILE="$HAMES_ROOT/.claude/.workspace_lock"
if [ ! -f "$LOCK_FILE" ]; then
    if [ "$DRY_RUN" = "1" ]; then
        echo "$prefix would create $LOCK_FILE"
    else
        mkdir -p "$(dirname "$LOCK_FILE")"
        echo '{"workspace": null, "locked": false}' > "$LOCK_FILE"
        echo "$prefix created .claude/.workspace_lock (lock OFF)"
    fi
fi

PATHS_FILE="$HAMES_ROOT/.claude/workspace_paths.json"
if [ ! -f "$PATHS_FILE" ]; then
    if [ "$DRY_RUN" = "1" ]; then
        echo "$prefix would create $PATHS_FILE"
    else
        cat > "$PATHS_FILE" <<EOF
{
  "schema_version": "paths-1.0",
  "hames_root": "$HAMES_ROOT",
  "workspaces": {},
  "_comment": "Auto-generated by init.sh. Add entries when you create workspaces under workspaces/."
}
EOF
        echo "$prefix created .claude/workspace_paths.json"
    fi
fi

# ── Step 4 — .env from .env.example ─────────────────────────────────────────
ENV_FILE="$HAMES_ROOT/arsenal/.env"
ENV_EXAMPLE="$HAMES_ROOT/arsenal/.env.example"
if [ -f "$ENV_EXAMPLE" ] && [ ! -f "$ENV_FILE" ]; then
    if [ "$DRY_RUN" = "1" ]; then
        echo "$prefix would copy arsenal/.env.example -> arsenal/.env"
    else
        cp "$ENV_EXAMPLE" "$ENV_FILE"
        echo "$prefix copied arsenal/.env.example -> arsenal/.env"
        echo "$prefix   ⚠  Fill arsenal/.env with your API keys (file is gitignored)"
    fi
fi

# ── Step 5 — npm install in arsenal/ ────────────────────────────────────────
if [ -f "$HAMES_ROOT/arsenal/package.json" ]; then
    if [ "$DRY_RUN" = "1" ]; then
        echo "$prefix would npm install in arsenal/"
    else
        echo "$prefix npm install in arsenal/..."
        if [ -f "$HAMES_ROOT/arsenal/package-lock.json" ]; then
            ( cd "$HAMES_ROOT/arsenal" && npm ci --no-audit --no-fund --loglevel=error ) \
                && echo "$prefix   npm dependencies OK" \
                || echo "$prefix   npm dependencies skipped or failed (optional dependencies unavailable)"
        else
            ( cd "$HAMES_ROOT/arsenal" && npm install --no-audit --no-fund --loglevel=error ) \
                && echo "$prefix   npm dependencies OK" \
                || echo "$prefix   npm dependencies skipped or failed (optional dependencies unavailable)"
        fi
    fi
fi

# ── Step 6 — Make hooks executable ──────────────────────────────────────────
if [ "$DRY_RUN" != "1" ]; then
    chmod +x "$HAMES_ROOT"/.claude/hooks/*.js 2>/dev/null || true
    chmod +x "$HAMES_ROOT"/arsenal/*.js 2>/dev/null || true
    chmod +x "$HAMES_ROOT"/arsenal/*.sh 2>/dev/null || true
    echo "$prefix made hooks executable"
fi

# ── Step 7 — verify_install.js ──────────────────────────────────────────────
VERIFY="$HAMES_ROOT/scripts/verify_install.js"
if [ -f "$VERIFY" ]; then
    if [ "$DRY_RUN" = "1" ]; then
        echo "$prefix would run scripts/verify_install.js"
    else
        echo ""
        echo "$prefix running install verification..."
        if ! node "$VERIFY"; then
            echo "$prefix VERIFICATION FAILED. Inspect output above." >&2
            exit 1
        fi
    fi
fi

echo ""
echo "============================================================================"
echo " Hames install complete."
echo "============================================================================"
echo ""
echo "Next steps:"
echo "  1. Edit arsenal/.env with your API keys (optional)"
echo "  2. In an AI client (Claude Code / Codex / Gemini CLI), open this directory"
echo "  3. Type: HamesSystem 적용  (or any first message) — defense lines activate"
echo "  4. Try: /doctor  — system integrity check"
echo ""

exit 0
